version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URL=mongodb://mongo:27017/database
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    command: npm start

  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./server/database:/docker-entrypoint-initdb.d

volumes:
  mongo_data:
